import Head from "next/head";
import { GraphQLClient, gql } from "graphql-request"

import Header from "../../components/Header";
import Footer from "../../components/Footer";

const graphcms = new GraphQLClient(process.env.GRAPHCMS_CONTENT_API);

const PAGE = gql`
    query Page($slug: String!){
        page(where: {slug: $slug}){
            id,
            title,
            slug,
            content{
                html
            }
        }
    }
`

const SLUGLIST = gql`
    {
        pages{
            slug
        }
    }
`

export async function getStaticPaths(){
    const {pages} = await graphcms.request(SLUGLIST);
    return {
        paths: pages.map((page) => ({params: {slug: page.slug}})),
        fallback: false
    }
}

export async function getStaticProps({params}){
    const slug = params.slug;
    const data = await graphcms.request(PAGE, {slug});
    const page = data.page;
    return {
        props: {
            page
        },
        revalidate: 10
    }
}

export default function Page({page}){
    return (
        <>

            <Head>
                <title>{`${page.title} - ${process.env.NEXT_PUBLIC_SITE_NAME}`}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />      
            </Head>

            <Header />

            <div className="my-24">
                <h1 className="font-bold text-3xl">{page.title}</h1>
                <div className="text-content text-gray-500 mt-5" dangerouslySetInnerHTML={{__html: page.content.html}} />
            </div>

            <Footer />
        </>
    )
}