import { useState, useEffect } from 'react';
import Head from 'next/head'
import { GraphQLClient, gql } from 'graphql-request'

const graphcms = new GraphQLClient(process.env.GRAPHCMS_CONTENT_API);
const WORKS = gql`
  {
    works{
      id,
      title,
      description,
      thumbnail{
        url
      }
    }
  }
`

const PROJECTS = gql`
  {
    projects{
      id,
      title,
      description,
      link,
      image{
        url
      }
    }
  }
`

const POSTS = gql`
{
  posts{
    id,
    title,
    date_published,
    slug,
    content{
      html
    },
    author{
      name,
      avatar{
        url
      }
    },
    coverPhoto{
      url
    },
    categories{
      id,
      title,
      slug
    }
  }
}  
`

import Header from '../components/Header'
import Hero from '../components/Hero'
import Works from '../components/Works'
import Projects from '../components/Projects'
import Posts from '../components/Posts'
import Footer from '../components/Footer';

export async function getServerSideProps(){
  const {works} = await graphcms.request(WORKS);
  const {projects} = await graphcms.request(PROJECTS);
  const {posts} = await graphcms.request(POSTS);
  return{
    props: {
      works,
      projects,
      posts
    },
    revalidate: 10
  }
}

export default function Home({works, projects, posts}) {
  return (
    <>
      <Head>
        <title>{process.env.NEXT_PUBLIC_SITE_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />      
      </Head>
      <Header />
      <Hero />
      <Works works={works} />
      <Projects projects={projects} />
      <Posts posts={posts} />
      <Footer />
    </>
  )
}
